imports:
    # - { resource: config_dev.yml }
    - { resource: config_prod.yml }
    - { resource: parameters_test.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    csrf_protection: true
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

services:
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }

swiftmailer:
    disable_delivery: true

oro_require_js:
    js_engine: ~