security:
    acl:
        connection: default
        cache:
            id: security.acl.cache.doctrine
            prefix: sf2_acl_

    access_decision_manager:
        strategy: unanimous

    encoders:
        Oro\Bundle\UserBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    # role_hierarchy:
    #     ROLE_ADMIN:       ROLE_USER
    #     ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers:                  [in_memory, oro_user]
        oro_user:
            id:                             oro_user.security.provider
        in_memory:
            memory:
                users: []
                    # user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    # admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        install:
            pattern:                        ^/installer
            security: false
            anonymous:                      true

        wsse_secured:
            pattern:                        ^/api/(rest|soap).*
            wsse:
                lifetime:                   3600
                realm:                      "Secured API"
                profile:                    "UsernameToken"
            context:                        main

        login:
            pattern:                        ^/user/(login|reset-request|send-email|check-email)$
            provider:                       chain_provider
            anonymous:                      true

        reset_password:
            pattern:                        ^/user/reset/*
            provider:                       chain_provider
            anonymous:                      true

        embedded_form:
            pattern:                        ^/embedded-form/(submit|success)
            provider:                       chain_provider
            anonymous:                      true

        tracking_data:
            pattern:                        ^/tracking/data/create
            provider:                       chain_provider
            anonymous:                      true

        main:
            pattern:                        ^/
            provider:                       chain_provider
            form_login:
                csrf_provider:              form.csrf_provider
                check_path:                 oro_user_security_check
                login_path:                 oro_user_security_login
            logout:
                path:                       oro_user_security_logout
            remember_me:
                key:                        %secret%
                name:                       BAPRM
                lifetime:                   1209600   # stay logged for two weeks
                httponly:                   true
            anonymous:                      false
        # demo_login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        # demo_secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:
        #         check_path: _demo_security_check
        #         login_path: _demo_login
        #     logout:
        #         path:   _demo_logout
        #         target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/rest/(latest|v1)/pinbars, role: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }